# .github/workflows/kali-vm.yml

name: Create Kali Linux Remote VM with Tailscale

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Kali Linux Environment
    runs-on: ubuntu-latest
    steps:
      - name: 1. Start Kali Linux Container
        run: |
          echo "### Starting Kali Linux Docker container in the background... ###"
          docker run --name kali -d -p 3389:3389 kalilinux/kali-rolling tail -f /dev/null
          sleep 15

      - name: 2. Install Dependencies (XRDP, Desktop, and Curl)
        run: |
          # Exit immediately if any command fails
          set -e
          echo "### Updating package lists... ###"
          docker exec kali apt-get update

          echo "### Installing packages... ###"
          docker exec kali apt-get install -y kali-desktop-xfce xrdp curl
          
      - name: 3. Configure User and Start XRDP
        run: |
          set -e
          echo "### Setting root password to 'kali' and starting XRDP service... ###"
          docker exec kali bash -c 'echo "root:kali" | chpasswd'
          docker exec kali bash -c "service xrdp start"

      - name: 4. Install and Connect Tailscale
        run: |
          set -e
          echo "### Installing Tailscale inside the container... ###"
          docker exec kali bash -c "curl -fsSL https://tailscale.com/install.sh | sh"
          
          echo "### Starting Tailscale and connecting to the tailnet... ###"
          # This command will now run separately. If the auth key is wrong,
          # the error message will be clearly visible in the logs for this step.
          docker exec kali tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-kali-vm
          
      - name: 5. Keep Workflow Alive
        run: |
          echo "####################################################################"
          echo "##  SUCCESS! The Kali VM is running and connected to your Tailscale network."
          echo "####################################################################"
          sleep 21600 # 6 hours
