# .github/workflows/kali-vm.yml

name: Create Kali Linux Remote VM with Tailscale

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Kali Linux Environment
    runs-on: ubuntu-latest
    steps:
      - name: 1. Start Kali Linux Container
        run: |
          echo "### Starting Kali Linux Docker container in the background... ###"
          docker run --name kali -d -p 3389:3389 kalilinux/kali-rolling tail -f /dev/null
          sleep 15

      - name: 2. Install Dependencies (XRDP, Desktop, and Curl)
        run: |
          echo "### Updating and installing dependencies... ###"
          docker exec kali bash -c "apt-get update && apt-get install -y kali-desktop-xfce xrdp curl"
          
      - name: 3. Configure User and Start XRDP
        run: |
          echo "### Setting root password to 'kali' and starting XRDP service... ###"
          docker exec kali bash -c 'echo "root:kali" | chpasswd'
          docker exec kali bash -c "service xrdp start"

      - name: 4. Install and Connect Tailscale
        run: |
          echo "### Installing Tailscale... ###"
          # Run the install script. It will place the files correctly.
          docker exec kali bash -c "curl -fsSL https://tailscale.com/install.sh | sh"

          echo "### Manually starting Tailscale daemon in background... ###"
          # Since there's no systemd, we start the daemon manually.
          # The 'docker exec -d' command runs the process in a detached (background) mode.
          docker exec -d kali tailscaled
          # Give the daemon a moment to initialize before we connect.
          sleep 5

          echo "### Connecting to the tailnet... ###"
          # Now that the daemon is running, we can connect the machine to our tailnet.
          docker exec kali bash -c "tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-kali-vm"
          
      - name: 5. Keep Workflow Alive
        run: |
          echo "####################################################################"
          echo "##  SUCCESS! The Kali VM is running and connected to your Tailscale network."
          echo "####################################################################"
          sleep 21600 # 6 hours
